#!/bin/bash
set -u

readonly EM_VERSION="v0.0.0"
readonly EM_THIS_CMD="${0##*/}"
readonly EM_THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-${(%):-%N}}")" && pwd)"
readonly EM_PLACEHOLDER='{}'
readonly EM_TEMPLATES=(
  "この{}を作ったのは誰だあっ!!"
  "突然の{} "
  "急に{}が来たので"
  "{}…そういうのもあるのか"
  "{}かわいいよ{}"
  "{}が死んでも代わりはいるもの"
  "{}に気づくとは…やはり天才か"
  "{}は素人なのですが質問よろしいでしょうか"
  "{}とダンスっちまった"
  "{}をセンターに入れてスイッチ..."
  "見ろ！人が{}のようだ！"
  "我思う、ゆえに{}あり"
  "{}は俺を怒らせた"
  "わぁい{}、{}大好き"
  "ゆっくり{}していってね！！！"
  "むしゃむしゃしていた。{}なら何でもよかった。"
  "身体は闘争を求める → {}が売れる → {}の新作が作られる"
  "我が生涯に一片の{}なし！"
  "はい今死んだ！今君の{}死んだよ！"
  "{}は爆発だ"
  "あきらめたらそこで{}だよ"
  "{}は人を傷つける。いつだって"
  "諸君らが愛してくれた{}は死んだ。なぜだ!？"
  "三十六計{}に如かず"
  "ざんねんながら{}はきえてしまいました"
  "だが{}は四天王の中で最弱"
  "吾輩は{}である。名前はまだ無い。"
  "{}は小説よりも奇なり"
  "高度に発達した{}は魔法と区別がつかない"
  "@@@TEMPLATE_INSERT_HERE@@@"
)

EM_command_version () {
  echo "${EM_THIS_CMD} ${EM_VERSION}"
}

EM_command_help () {
  cat << _EOS_
Usage:
  ${EM_THIS_CMD} [OPTIONS] MESSAGE

OPTIONS:
  --help       Display this help and exit
  --version    Output version information and exit
  -s           Read message from stdin
  -r           Send request to register new meme (see REGISTER MEME)

REGISTER MEME:
  '{}' is the placeholder of the message.
  For example,
    $ sudo ${EM_THIS_CMD} -r 'こんにちは{}、ありがとう{}'
  It displays the URL to send the pull-request to the ${EM_THIS_CMD} repository.
    https://github.com/greymd/echo-meme/issues/new...

_EOS_

}

EM_urlenc () {
  local _payload="$1"
  printf "%s" "$_payload" | od -v -An -tx1 | xargs | tr ' ' '%' | sed 's/^/%/' | tr '[:lower:]' '[:upper:]'
}

EM_command_register_global () {
  local _title="$1" ;shift
  local _body="$1" ;shift
  echo "https://github.com/greymd/echo-meme/issues/new?body=$(EM_urlenc "$_body")&title=$(EM_urlenc "$_title")"
}

EM_command_echo () {
  local _msg="$1"
  shift
  local _num_templates="${#EM_TEMPLATES[@]}"
  # - 1 to hide "@@@TEMPLATE_INSERT_HERE@@@"
  local _print_target_index="$(( RANDOM % ( _num_templates - 1 ) ))"
  # RANDOM range is 0 - 32767. take care.
  local _print_message="${EM_TEMPLATES[${_print_target_index}]}"
  printf "%s\\n" "${_print_message//$EM_PLACEHOLDER/${_msg}}"
}

EM_check_message_before_register() {
  local _msg="$1"
  if [[ -z "$_msg" ]]; then
    EM_command_help
    EM_msg_error "Empty message is not allowed"
    return 1
  fi
  if ! [[ "$_msg" =~ {} ]]; then
    EM_command_help
    EM_msg_error "Message does not include placeholder '$EM_PLACEHOLDER'"
    return 1
  fi
}

EM_msg() {
  local _loglevel="$1"
  local _msgbody="$2"
  local _msg="${EM_THIS_CMD}:${_loglevel}: ${_msgbody}"
  printf "%s\\n" "${_msg}" >&2
}

EM_msg_info() {
  EM_msg "Info" "$1"
}

EM_msg_error() {
  EM_msg "Error" "$1"
}

EM_main () {
  local _opt_register_global=0
  local _msg=""
  while (( $# > 0 )); do
    local _opt="$1"; shift
    case "$_opt" in
      --help)
        EM_command_help
        return 0
        ;;
      --version)
        EM_command_version
        return 0
        ;;
      -s)
        if [[ -n "$_msg" ]]; then
          EM_command_help
          EM_msg_error "Invalid argument '$_msg'"
          return 1
        fi
        _msg="$(cat)"
        ;;
      -r)
        _opt_register_global=1
        ;;
      *)
        if [[ -n "$_msg" ]]; then
          EM_command_help
          EM_msg_error "Invalid argument '$_msg'"
          return 1
        fi
        _msg="$_opt"
        ;;
    esac
  done
  if [[ $_opt_register_global -eq 1 ]]; then
    EM_check_message_before_register "${_msg}" || return 1
    EM_msg_info "Open this URL and just click [Submit this issue]! Do not hesiate."
    EM_command_register_global "New meme request:${_msg}" "Template:${_msg}"
    return 0
  fi
  _msg="${_msg:-$USER}"
  EM_command_echo "${_msg}"
}

EM_main "${1+"$@"}"
exit $?
